// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob.proto

package protob

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MatchType int32

const (
	MatchType_NONE            MatchType = 0
	MatchType_EXACT           MatchType = 1
	MatchType_CANONICAL_EXACT MatchType = 2
	MatchType_CANONICAL_FUZZY MatchType = 3
	MatchType_PARTIAL_EXACT   MatchType = 4
	MatchType_PARTIAL_FUZZY   MatchType = 5
)

var MatchType_name = map[int32]string{
	0: "NONE",
	1: "EXACT",
	2: "CANONICAL_EXACT",
	3: "CANONICAL_FUZZY",
	4: "PARTIAL_EXACT",
	5: "PARTIAL_FUZZY",
}

var MatchType_value = map[string]int32{
	"NONE":            0,
	"EXACT":           1,
	"CANONICAL_EXACT": 2,
	"CANONICAL_FUZZY": 3,
	"PARTIAL_EXACT":   4,
	"PARTIAL_FUZZY":   5,
}

func (x MatchType) String() string {
	return proto.EnumName(MatchType_name, int32(x))
}

func (MatchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{0}
}

type Pong struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{0}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{1}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type WithDetails struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithDetails) Reset()         { *m = WithDetails{} }
func (m *WithDetails) String() string { return proto.CompactTextString(m) }
func (*WithDetails) ProtoMessage()    {}
func (*WithDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{2}
}

func (m *WithDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithDetails.Unmarshal(m, b)
}
func (m *WithDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithDetails.Marshal(b, m, deterministic)
}
func (m *WithDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithDetails.Merge(m, src)
}
func (m *WithDetails) XXX_Size() int {
	return xxx_messageInfo_WithDetails.Size(m)
}
func (m *WithDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_WithDetails.DiscardUnknown(m)
}

var xxx_messageInfo_WithDetails proto.InternalMessageInfo

func (m *WithDetails) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type WithLanguage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithLanguage) Reset()         { *m = WithLanguage{} }
func (m *WithLanguage) String() string { return proto.CompactTextString(m) }
func (*WithLanguage) ProtoMessage()    {}
func (*WithLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{3}
}

func (m *WithLanguage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithLanguage.Unmarshal(m, b)
}
func (m *WithLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithLanguage.Marshal(b, m, deterministic)
}
func (m *WithLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithLanguage.Merge(m, src)
}
func (m *WithLanguage) XXX_Size() int {
	return xxx_messageInfo_WithLanguage.Size(m)
}
func (m *WithLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_WithLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_WithLanguage proto.InternalMessageInfo

func (m *WithLanguage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WithVerification struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithVerification) Reset()         { *m = WithVerification{} }
func (m *WithVerification) String() string { return proto.CompactTextString(m) }
func (*WithVerification) ProtoMessage()    {}
func (*WithVerification) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{4}
}

func (m *WithVerification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithVerification.Unmarshal(m, b)
}
func (m *WithVerification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithVerification.Marshal(b, m, deterministic)
}
func (m *WithVerification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithVerification.Merge(m, src)
}
func (m *WithVerification) XXX_Size() int {
	return xxx_messageInfo_WithVerification.Size(m)
}
func (m *WithVerification) XXX_DiscardUnknown() {
	xxx_messageInfo_WithVerification.DiscardUnknown(m)
}

var xxx_messageInfo_WithVerification proto.InternalMessageInfo

func (m *WithVerification) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Params struct {
	Text                 []byte            `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	WithDetails          *WithDetails      `protobuf:"bytes,2,opt,name=with_details,json=withDetails,proto3" json:"with_details,omitempty"`
	Language             *WithLanguage     `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	WithVerification     *WithVerification `protobuf:"bytes,4,opt,name=with_verification,json=withVerification,proto3" json:"with_verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{5}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Params) GetWithDetails() *WithDetails {
	if m != nil {
		return m.WithDetails
	}
	return nil
}

func (m *Params) GetLanguage() *WithLanguage {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *Params) GetWithVerification() *WithVerification {
	if m != nil {
		return m.WithVerification
	}
	return nil
}

type NameStrings struct {
	Text                 []byte        `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Names                []*NameString `protobuf:"bytes,6,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NameStrings) Reset()         { *m = NameStrings{} }
func (m *NameStrings) String() string { return proto.CompactTextString(m) }
func (*NameStrings) ProtoMessage()    {}
func (*NameStrings) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{6}
}

func (m *NameStrings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameStrings.Unmarshal(m, b)
}
func (m *NameStrings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameStrings.Marshal(b, m, deterministic)
}
func (m *NameStrings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameStrings.Merge(m, src)
}
func (m *NameStrings) XXX_Size() int {
	return xxx_messageInfo_NameStrings.Size(m)
}
func (m *NameStrings) XXX_DiscardUnknown() {
	xxx_messageInfo_NameStrings.DiscardUnknown(m)
}

var xxx_messageInfo_NameStrings proto.InternalMessageInfo

func (m *NameStrings) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *NameStrings) GetNames() []*NameString {
	if m != nil {
		return m.Names
	}
	return nil
}

type NameString struct {
	Value                string    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Odds                 float32   `protobuf:"fixed32,2,opt,name=odds,proto3" json:"odds,omitempty"`
	Path                 string    `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Curated              bool      `protobuf:"varint,4,opt,name=curated,proto3" json:"curated,omitempty"`
	EditDistance         int32     `protobuf:"varint,5,opt,name=edit_distance,json=editDistance,proto3" json:"edit_distance,omitempty"`
	EditDistanceStem     int32     `protobuf:"varint,6,opt,name=edit_distance_stem,json=editDistanceStem,proto3" json:"edit_distance_stem,omitempty"`
	SourceId             int32     `protobuf:"varint,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Match                MatchType `protobuf:"varint,8,opt,name=match,proto3,enum=protob.MatchType" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NameString) Reset()         { *m = NameString{} }
func (m *NameString) String() string { return proto.CompactTextString(m) }
func (*NameString) ProtoMessage()    {}
func (*NameString) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{7}
}

func (m *NameString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameString.Unmarshal(m, b)
}
func (m *NameString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameString.Marshal(b, m, deterministic)
}
func (m *NameString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameString.Merge(m, src)
}
func (m *NameString) XXX_Size() int {
	return xxx_messageInfo_NameString.Size(m)
}
func (m *NameString) XXX_DiscardUnknown() {
	xxx_messageInfo_NameString.DiscardUnknown(m)
}

var xxx_messageInfo_NameString proto.InternalMessageInfo

func (m *NameString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NameString) GetOdds() float32 {
	if m != nil {
		return m.Odds
	}
	return 0
}

func (m *NameString) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *NameString) GetCurated() bool {
	if m != nil {
		return m.Curated
	}
	return false
}

func (m *NameString) GetEditDistance() int32 {
	if m != nil {
		return m.EditDistance
	}
	return 0
}

func (m *NameString) GetEditDistanceStem() int32 {
	if m != nil {
		return m.EditDistanceStem
	}
	return 0
}

func (m *NameString) GetSourceId() int32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *NameString) GetMatch() MatchType {
	if m != nil {
		return m.Match
	}
	return MatchType_NONE
}

func init() {
	proto.RegisterEnum("protob.MatchType", MatchType_name, MatchType_value)
	proto.RegisterType((*Pong)(nil), "protob.Pong")
	proto.RegisterType((*Void)(nil), "protob.Void")
	proto.RegisterType((*WithDetails)(nil), "protob.WithDetails")
	proto.RegisterType((*WithLanguage)(nil), "protob.WithLanguage")
	proto.RegisterType((*WithVerification)(nil), "protob.WithVerification")
	proto.RegisterType((*Params)(nil), "protob.Params")
	proto.RegisterType((*NameStrings)(nil), "protob.NameStrings")
	proto.RegisterType((*NameString)(nil), "protob.NameString")
}

func init() { proto.RegisterFile("protob.proto", fileDescriptor_e471450a6e94b5eb) }

var fileDescriptor_e471450a6e94b5eb = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x51, 0x6f, 0xda, 0x3c,
	0x14, 0x86, 0x09, 0x24, 0x34, 0x39, 0xa4, 0xfd, 0x82, 0xe9, 0x85, 0xd5, 0x6f, 0x17, 0x28, 0xad,
	0xb4, 0x68, 0x9a, 0xaa, 0x89, 0x49, 0xbb, 0x47, 0x94, 0x4e, 0x68, 0x5d, 0x8a, 0x5c, 0xd6, 0x6d,
	0xbd, 0x41, 0x2e, 0xf6, 0xc0, 0x12, 0x49, 0x50, 0x62, 0xca, 0xf6, 0x23, 0xf7, 0x93, 0x26, 0x4d,
	0xb6, 0x09, 0x84, 0x6d, 0xbd, 0x8a, 0xcf, 0xeb, 0xe7, 0xd8, 0xef, 0x39, 0xce, 0x01, 0x7f, 0x95,
	0x67, 0x32, 0x7b, 0xbc, 0xd4, 0x1f, 0xd4, 0x34, 0x51, 0xf8, 0x02, 0xec, 0x71, 0x96, 0xce, 0xd1,
	0x29, 0x38, 0x4f, 0x74, 0xb9, 0xe6, 0xd8, 0xea, 0x5a, 0x91, 0x47, 0x4c, 0x10, 0x36, 0xc1, 0xbe,
	0xcf, 0x04, 0x0b, 0xcf, 0xa1, 0xf5, 0x59, 0xc8, 0xc5, 0x15, 0x97, 0x54, 0x2c, 0x8b, 0x43, 0xd8,
	0x2d, 0xe1, 0x0b, 0xf0, 0x15, 0x74, 0x43, 0xd3, 0xf9, 0x9a, 0xce, 0xf9, 0x33, 0x47, 0x46, 0x10,
	0x28, 0xea, 0x9e, 0xe7, 0xe2, 0x9b, 0x98, 0x51, 0x29, 0xb2, 0xf4, 0x99, 0xf3, 0x7e, 0x5a, 0xd0,
	0x1c, 0xd3, 0x9c, 0x26, 0x05, 0x42, 0x60, 0x4b, 0xfe, 0x5d, 0xea, 0x7d, 0x9f, 0xe8, 0x35, 0x7a,
	0x07, 0xfe, 0x46, 0xc8, 0xc5, 0x94, 0x19, 0x53, 0xb8, 0xde, 0xb5, 0xa2, 0x56, 0xaf, 0x73, 0xb9,
	0x2d, 0xb3, 0xe2, 0x97, 0xb4, 0x36, 0x15, 0xf3, 0x6f, 0xc0, 0x5d, 0x6e, 0x2d, 0xe2, 0x86, 0xce,
	0x39, 0xad, 0xe6, 0x94, 0xf6, 0xc9, 0x8e, 0x42, 0x43, 0x68, 0xeb, 0x9b, 0x9e, 0x2a, 0x9e, 0xb1,
	0xad, 0x53, 0x71, 0x35, 0xb5, 0x5a, 0x13, 0x09, 0x36, 0x7f, 0x28, 0xe1, 0x07, 0x68, 0xc5, 0x34,
	0xe1, 0x77, 0x32, 0x17, 0xe9, 0x7c, 0x5f, 0x53, 0xa3, 0x52, 0x53, 0x04, 0x4e, 0x4a, 0x13, 0x5e,
	0xe0, 0x66, 0xb7, 0x11, 0xb5, 0x7a, 0xa8, 0x3c, 0x7d, 0x9f, 0x47, 0x0c, 0x10, 0xfe, 0xb2, 0x00,
	0xf6, 0xea, 0xbf, 0x7b, 0xad, 0xae, 0xc8, 0x18, 0x33, 0xad, 0xa9, 0x13, 0xbd, 0x56, 0xda, 0x8a,
	0xca, 0x85, 0xbe, 0xd6, 0x23, 0x7a, 0x8d, 0x30, 0x1c, 0xcd, 0xd6, 0x39, 0x95, 0x9c, 0xe9, 0xb2,
	0x5c, 0x52, 0x86, 0xe8, 0x1c, 0x8e, 0x39, 0x13, 0x72, 0xca, 0x44, 0x21, 0x69, 0x3a, 0xe3, 0xd8,
	0xe9, 0x5a, 0x91, 0x43, 0x7c, 0x25, 0x5e, 0x6d, 0x35, 0xf4, 0x1a, 0xd0, 0x01, 0x34, 0x2d, 0x24,
	0x4f, 0x70, 0x53, 0x93, 0x41, 0x95, 0xbc, 0x93, 0x3c, 0x41, 0xff, 0x83, 0x57, 0x64, 0xeb, 0x7c,
	0xc6, 0xa7, 0x82, 0xe1, 0x23, 0x0d, 0xb9, 0x46, 0x18, 0x31, 0xf4, 0x12, 0x9c, 0x84, 0xca, 0xd9,
	0x02, 0xbb, 0x5d, 0x2b, 0x3a, 0xe9, 0xb5, 0xcb, 0x06, 0x7c, 0x54, 0xe2, 0xe4, 0xc7, 0x8a, 0x13,
	0xb3, 0xff, 0x6a, 0x05, 0xde, 0x4e, 0x43, 0x2e, 0xd8, 0xf1, 0x6d, 0x3c, 0x0c, 0x6a, 0xc8, 0x03,
	0x67, 0xf8, 0xa5, 0x3f, 0x98, 0x04, 0x16, 0xea, 0xc0, 0x7f, 0x83, 0x7e, 0x7c, 0x1b, 0x8f, 0x06,
	0xfd, 0x9b, 0xa9, 0x11, 0xeb, 0x87, 0xe2, 0xf5, 0xa7, 0x87, 0x87, 0xaf, 0x41, 0x03, 0xb5, 0xe1,
	0x78, 0xdc, 0x27, 0x93, 0xd1, 0x8e, 0xb3, 0xab, 0x92, 0xa1, 0x9c, 0x1e, 0x03, 0xf7, 0x7d, 0x7c,
	0x2d, 0x52, 0xc6, 0x73, 0x74, 0x01, 0xf6, 0x58, 0xb5, 0xdd, 0x2f, 0xfd, 0xa9, 0x29, 0x39, 0xdb,
	0x45, 0x6a, 0xa2, 0xc2, 0x1a, 0xea, 0x81, 0xa7, 0x78, 0xf5, 0x4c, 0x05, 0x3a, 0xd9, 0x6d, 0xea,
	0x5f, 0xfa, 0xac, 0xf3, 0xf7, 0xdb, 0x16, 0x61, 0xed, 0xd1, 0xcc, 0xe5, 0xdb, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xb5, 0x76, 0x2b, 0xa1, 0xae, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GNFinderClient is the client API for GNFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GNFinderClient interface {
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error)
	FindNames(ctx context.Context, in *Params, opts ...grpc.CallOption) (*NameStrings, error)
}

type gNFinderClient struct {
	cc *grpc.ClientConn
}

func NewGNFinderClient(cc *grpc.ClientConn) GNFinderClient {
	return &gNFinderClient{cc}
}

func (c *gNFinderClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/protob.GNFinder/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNFinderClient) FindNames(ctx context.Context, in *Params, opts ...grpc.CallOption) (*NameStrings, error) {
	out := new(NameStrings)
	err := c.cc.Invoke(ctx, "/protob.GNFinder/FindNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GNFinderServer is the server API for GNFinder service.
type GNFinderServer interface {
	Ping(context.Context, *Void) (*Pong, error)
	FindNames(context.Context, *Params) (*NameStrings, error)
}

func RegisterGNFinderServer(s *grpc.Server, srv GNFinderServer) {
	s.RegisterService(&_GNFinder_serviceDesc, srv)
}

func _GNFinder_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNFinderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNFinder/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNFinderServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNFinder_FindNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNFinderServer).FindNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNFinder/FindNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNFinderServer).FindNames(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

var _GNFinder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protob.GNFinder",
	HandlerType: (*GNFinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GNFinder_Ping_Handler,
		},
		{
			MethodName: "FindNames",
			Handler:    _GNFinder_FindNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protob.proto",
}
