// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob.proto

package protob

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchType int32

const (
	MatchType_NONE          MatchType = 0
	MatchType_EXACT         MatchType = 1
	MatchType_FUZZY         MatchType = 2
	MatchType_PARTIAL_EXACT MatchType = 3
	MatchType_PARTIAL_FUZZY MatchType = 4
)

var MatchType_name = map[int32]string{
	0: "NONE",
	1: "EXACT",
	2: "FUZZY",
	3: "PARTIAL_EXACT",
	4: "PARTIAL_FUZZY",
}

var MatchType_value = map[string]int32{
	"NONE":          0,
	"EXACT":         1,
	"FUZZY":         2,
	"PARTIAL_EXACT": 3,
	"PARTIAL_FUZZY": 4,
}

func (x MatchType) String() string {
	return proto.EnumName(MatchType_name, int32(x))
}

func (MatchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{0}
}

type AnnotNomenType int32

const (
	AnnotNomenType_NO_ANNOT  AnnotNomenType = 0
	AnnotNomenType_SP_NOV    AnnotNomenType = 1
	AnnotNomenType_COMB_NOV  AnnotNomenType = 2
	AnnotNomenType_SUBSP_NOV AnnotNomenType = 3
)

var AnnotNomenType_name = map[int32]string{
	0: "NO_ANNOT",
	1: "SP_NOV",
	2: "COMB_NOV",
	3: "SUBSP_NOV",
}

var AnnotNomenType_value = map[string]int32{
	"NO_ANNOT":  0,
	"SP_NOV":    1,
	"COMB_NOV":  2,
	"SUBSP_NOV": 3,
}

func (x AnnotNomenType) String() string {
	return proto.EnumName(AnnotNomenType_name, int32(x))
}

func (AnnotNomenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{1}
}

type Approach int32

const (
	Approach_HEURISTIC Approach = 0
	Approach_BAYES     Approach = 1
)

var Approach_name = map[int32]string{
	0: "HEURISTIC",
	1: "BAYES",
}

var Approach_value = map[string]int32{
	"HEURISTIC": 0,
	"BAYES":     1,
}

func (x Approach) String() string {
	return proto.EnumName(Approach_name, int32(x))
}

func (Approach) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{2}
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type Pong struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Version struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Build                string   `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{2}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

type Params struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	NoBayes              bool     `protobuf:"varint,2,opt,name=no_bayes,json=noBayes,proto3" json:"no_bayes,omitempty"`
	Language             string   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	DetectLanguage       bool     `protobuf:"varint,4,opt,name=detect_language,json=detectLanguage,proto3" json:"detect_language,omitempty"`
	Verification         bool     `protobuf:"varint,5,opt,name=verification,proto3" json:"verification,omitempty"`
	TokensAround         int32    `protobuf:"varint,6,opt,name=tokens_around,json=tokensAround,proto3" json:"tokens_around,omitempty"`
	Sources              []int32  `protobuf:"varint,7,rep,packed,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{3}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Params) GetNoBayes() bool {
	if m != nil {
		return m.NoBayes
	}
	return false
}

func (m *Params) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Params) GetDetectLanguage() bool {
	if m != nil {
		return m.DetectLanguage
	}
	return false
}

func (m *Params) GetVerification() bool {
	if m != nil {
		return m.Verification
	}
	return false
}

func (m *Params) GetTokensAround() int32 {
	if m != nil {
		return m.TokensAround
	}
	return 0
}

func (m *Params) GetSources() []int32 {
	if m != nil {
		return m.Sources
	}
	return nil
}

type Output struct {
	Date                 string        `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	FinderVersion        string        `protobuf:"bytes,2,opt,name=finder_version,json=finderVersion,proto3" json:"finder_version,omitempty"`
	Approach             []Approach    `protobuf:"varint,3,rep,packed,name=approach,proto3,enum=protob.Approach" json:"approach,omitempty"`
	TokensAround         int32         `protobuf:"varint,4,opt,name=tokens_around,json=tokensAround,proto3" json:"tokens_around,omitempty"`
	Language             string        `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	LanguageDetected     string        `protobuf:"bytes,6,opt,name=language_detected,json=languageDetected,proto3" json:"language_detected,omitempty"`
	DetectLanguage       bool          `protobuf:"varint,7,opt,name=detect_language,json=detectLanguage,proto3" json:"detect_language,omitempty"`
	TotalTokens          int32         `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCandidates      int32         `protobuf:"varint,9,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`
	TotalNames           int32         `protobuf:"varint,10,opt,name=total_names,json=totalNames,proto3" json:"total_names,omitempty"`
	Names                []*NameString `protobuf:"bytes,11,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{4}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Output) GetFinderVersion() string {
	if m != nil {
		return m.FinderVersion
	}
	return ""
}

func (m *Output) GetApproach() []Approach {
	if m != nil {
		return m.Approach
	}
	return nil
}

func (m *Output) GetTokensAround() int32 {
	if m != nil {
		return m.TokensAround
	}
	return 0
}

func (m *Output) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Output) GetLanguageDetected() string {
	if m != nil {
		return m.LanguageDetected
	}
	return ""
}

func (m *Output) GetDetectLanguage() bool {
	if m != nil {
		return m.DetectLanguage
	}
	return false
}

func (m *Output) GetTotalTokens() int32 {
	if m != nil {
		return m.TotalTokens
	}
	return 0
}

func (m *Output) GetTotalCandidates() int32 {
	if m != nil {
		return m.TotalCandidates
	}
	return 0
}

func (m *Output) GetTotalNames() int32 {
	if m != nil {
		return m.TotalNames
	}
	return 0
}

func (m *Output) GetNames() []*NameString {
	if m != nil {
		return m.Names
	}
	return nil
}

type NameString struct {
	Cardinality          int32          `protobuf:"varint,1,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	Verbatim             string         `protobuf:"bytes,3,opt,name=verbatim,proto3" json:"verbatim,omitempty"`
	Name                 string         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Odds                 float32        `protobuf:"fixed32,5,opt,name=odds,proto3" json:"odds,omitempty"`
	AnnotNomen           string         `protobuf:"bytes,6,opt,name=annot_nomen,json=annotNomen,proto3" json:"annot_nomen,omitempty"`
	AnnotNomenType       AnnotNomenType `protobuf:"varint,7,opt,name=annot_nomen_type,json=annotNomenType,proto3,enum=protob.AnnotNomenType" json:"annot_nomen_type,omitempty"`
	OffsetStart          int32          `protobuf:"varint,8,opt,name=offset_start,json=offsetStart,proto3" json:"offset_start,omitempty"`
	OffsetEnd            int32          `protobuf:"varint,9,opt,name=offset_end,json=offsetEnd,proto3" json:"offset_end,omitempty"`
	WordsBefore          []string       `protobuf:"bytes,10,rep,name=words_before,json=wordsBefore,proto3" json:"words_before,omitempty"`
	WordsAfter           []string       `protobuf:"bytes,11,rep,name=words_after,json=wordsAfter,proto3" json:"words_after,omitempty"`
	Verification         *Verification  `protobuf:"bytes,12,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NameString) Reset()         { *m = NameString{} }
func (m *NameString) String() string { return proto.CompactTextString(m) }
func (*NameString) ProtoMessage()    {}
func (*NameString) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{5}
}

func (m *NameString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameString.Unmarshal(m, b)
}
func (m *NameString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameString.Marshal(b, m, deterministic)
}
func (m *NameString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameString.Merge(m, src)
}
func (m *NameString) XXX_Size() int {
	return xxx_messageInfo_NameString.Size(m)
}
func (m *NameString) XXX_DiscardUnknown() {
	xxx_messageInfo_NameString.DiscardUnknown(m)
}

var xxx_messageInfo_NameString proto.InternalMessageInfo

func (m *NameString) GetCardinality() int32 {
	if m != nil {
		return m.Cardinality
	}
	return 0
}

func (m *NameString) GetVerbatim() string {
	if m != nil {
		return m.Verbatim
	}
	return ""
}

func (m *NameString) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameString) GetOdds() float32 {
	if m != nil {
		return m.Odds
	}
	return 0
}

func (m *NameString) GetAnnotNomen() string {
	if m != nil {
		return m.AnnotNomen
	}
	return ""
}

func (m *NameString) GetAnnotNomenType() AnnotNomenType {
	if m != nil {
		return m.AnnotNomenType
	}
	return AnnotNomenType_NO_ANNOT
}

func (m *NameString) GetOffsetStart() int32 {
	if m != nil {
		return m.OffsetStart
	}
	return 0
}

func (m *NameString) GetOffsetEnd() int32 {
	if m != nil {
		return m.OffsetEnd
	}
	return 0
}

func (m *NameString) GetWordsBefore() []string {
	if m != nil {
		return m.WordsBefore
	}
	return nil
}

func (m *NameString) GetWordsAfter() []string {
	if m != nil {
		return m.WordsAfter
	}
	return nil
}

func (m *NameString) GetVerification() *Verification {
	if m != nil {
		return m.Verification
	}
	return nil
}

type Verification struct {
	BestResult           *ResultData   `protobuf:"bytes,1,opt,name=best_result,json=bestResult,proto3" json:"best_result,omitempty"`
	PreferredResults     []*ResultData `protobuf:"bytes,2,rep,name=preferred_results,json=preferredResults,proto3" json:"preferred_results,omitempty"`
	DataSourcesNum       int32         `protobuf:"varint,3,opt,name=data_sources_num,json=dataSourcesNum,proto3" json:"data_sources_num,omitempty"`
	DataSourceQuality    string        `protobuf:"bytes,4,opt,name=data_source_quality,json=dataSourceQuality,proto3" json:"data_source_quality,omitempty"`
	Retries              int32         `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	Error                string        `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Verification) Reset()         { *m = Verification{} }
func (m *Verification) String() string { return proto.CompactTextString(m) }
func (*Verification) ProtoMessage()    {}
func (*Verification) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{6}
}

func (m *Verification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verification.Unmarshal(m, b)
}
func (m *Verification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verification.Marshal(b, m, deterministic)
}
func (m *Verification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verification.Merge(m, src)
}
func (m *Verification) XXX_Size() int {
	return xxx_messageInfo_Verification.Size(m)
}
func (m *Verification) XXX_DiscardUnknown() {
	xxx_messageInfo_Verification.DiscardUnknown(m)
}

var xxx_messageInfo_Verification proto.InternalMessageInfo

func (m *Verification) GetBestResult() *ResultData {
	if m != nil {
		return m.BestResult
	}
	return nil
}

func (m *Verification) GetPreferredResults() []*ResultData {
	if m != nil {
		return m.PreferredResults
	}
	return nil
}

func (m *Verification) GetDataSourcesNum() int32 {
	if m != nil {
		return m.DataSourcesNum
	}
	return 0
}

func (m *Verification) GetDataSourceQuality() string {
	if m != nil {
		return m.DataSourceQuality
	}
	return ""
}

func (m *Verification) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *Verification) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResultData struct {
	DataSourceId           int32     `protobuf:"varint,1,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	DataSourceTitle        string    `protobuf:"bytes,2,opt,name=data_source_title,json=dataSourceTitle,proto3" json:"data_source_title,omitempty"`
	TaxonId                string    `protobuf:"bytes,3,opt,name=taxon_id,json=taxonId,proto3" json:"taxon_id,omitempty"`
	MatchedName            string    `protobuf:"bytes,4,opt,name=matched_name,json=matchedName,proto3" json:"matched_name,omitempty"`
	MatchedCardinality     int32     `protobuf:"varint,5,opt,name=matched_cardinality,json=matchedCardinality,proto3" json:"matched_cardinality,omitempty"`
	MatchedCanonicalSimple string    `protobuf:"bytes,6,opt,name=matched_canonical_simple,json=matchedCanonicalSimple,proto3" json:"matched_canonical_simple,omitempty"`
	MatchedCanonicalFull   string    `protobuf:"bytes,7,opt,name=matched_canonical_full,json=matchedCanonicalFull,proto3" json:"matched_canonical_full,omitempty"`
	CurrentName            string    `protobuf:"bytes,8,opt,name=current_name,json=currentName,proto3" json:"current_name,omitempty"`
	CurrentCardinality     int32     `protobuf:"varint,9,opt,name=current_cardinality,json=currentCardinality,proto3" json:"current_cardinality,omitempty"`
	CurrentCanonicalSimple string    `protobuf:"bytes,10,opt,name=current_canonical_simple,json=currentCanonicalSimple,proto3" json:"current_canonical_simple,omitempty"`
	CurrentCanonicalFull   string    `protobuf:"bytes,11,opt,name=current_canonical_full,json=currentCanonicalFull,proto3" json:"current_canonical_full,omitempty"`
	Synonym                bool      `protobuf:"varint,12,opt,name=synonym,proto3" json:"synonym,omitempty"`
	ClassificationPath     string    `protobuf:"bytes,13,opt,name=classification_path,json=classificationPath,proto3" json:"classification_path,omitempty"`
	ClassificationRank     string    `protobuf:"bytes,14,opt,name=classification_rank,json=classificationRank,proto3" json:"classification_rank,omitempty"`
	ClassificationIds      string    `protobuf:"bytes,15,opt,name=classification_ids,json=classificationIds,proto3" json:"classification_ids,omitempty"`
	EditDistance           int32     `protobuf:"varint,16,opt,name=edit_distance,json=editDistance,proto3" json:"edit_distance,omitempty"`
	StemEditDistance       int32     `protobuf:"varint,17,opt,name=stem_edit_distance,json=stemEditDistance,proto3" json:"stem_edit_distance,omitempty"`
	MatchType              MatchType `protobuf:"varint,18,opt,name=match_type,json=matchType,proto3,enum=protob.MatchType" json:"match_type,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}  `json:"-"`
	XXX_unrecognized       []byte    `json:"-"`
	XXX_sizecache          int32     `json:"-"`
}

func (m *ResultData) Reset()         { *m = ResultData{} }
func (m *ResultData) String() string { return proto.CompactTextString(m) }
func (*ResultData) ProtoMessage()    {}
func (*ResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e471450a6e94b5eb, []int{7}
}

func (m *ResultData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultData.Unmarshal(m, b)
}
func (m *ResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultData.Marshal(b, m, deterministic)
}
func (m *ResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultData.Merge(m, src)
}
func (m *ResultData) XXX_Size() int {
	return xxx_messageInfo_ResultData.Size(m)
}
func (m *ResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultData.DiscardUnknown(m)
}

var xxx_messageInfo_ResultData proto.InternalMessageInfo

func (m *ResultData) GetDataSourceId() int32 {
	if m != nil {
		return m.DataSourceId
	}
	return 0
}

func (m *ResultData) GetDataSourceTitle() string {
	if m != nil {
		return m.DataSourceTitle
	}
	return ""
}

func (m *ResultData) GetTaxonId() string {
	if m != nil {
		return m.TaxonId
	}
	return ""
}

func (m *ResultData) GetMatchedName() string {
	if m != nil {
		return m.MatchedName
	}
	return ""
}

func (m *ResultData) GetMatchedCardinality() int32 {
	if m != nil {
		return m.MatchedCardinality
	}
	return 0
}

func (m *ResultData) GetMatchedCanonicalSimple() string {
	if m != nil {
		return m.MatchedCanonicalSimple
	}
	return ""
}

func (m *ResultData) GetMatchedCanonicalFull() string {
	if m != nil {
		return m.MatchedCanonicalFull
	}
	return ""
}

func (m *ResultData) GetCurrentName() string {
	if m != nil {
		return m.CurrentName
	}
	return ""
}

func (m *ResultData) GetCurrentCardinality() int32 {
	if m != nil {
		return m.CurrentCardinality
	}
	return 0
}

func (m *ResultData) GetCurrentCanonicalSimple() string {
	if m != nil {
		return m.CurrentCanonicalSimple
	}
	return ""
}

func (m *ResultData) GetCurrentCanonicalFull() string {
	if m != nil {
		return m.CurrentCanonicalFull
	}
	return ""
}

func (m *ResultData) GetSynonym() bool {
	if m != nil {
		return m.Synonym
	}
	return false
}

func (m *ResultData) GetClassificationPath() string {
	if m != nil {
		return m.ClassificationPath
	}
	return ""
}

func (m *ResultData) GetClassificationRank() string {
	if m != nil {
		return m.ClassificationRank
	}
	return ""
}

func (m *ResultData) GetClassificationIds() string {
	if m != nil {
		return m.ClassificationIds
	}
	return ""
}

func (m *ResultData) GetEditDistance() int32 {
	if m != nil {
		return m.EditDistance
	}
	return 0
}

func (m *ResultData) GetStemEditDistance() int32 {
	if m != nil {
		return m.StemEditDistance
	}
	return 0
}

func (m *ResultData) GetMatchType() MatchType {
	if m != nil {
		return m.MatchType
	}
	return MatchType_NONE
}

func init() {
	proto.RegisterEnum("protob.MatchType", MatchType_name, MatchType_value)
	proto.RegisterEnum("protob.AnnotNomenType", AnnotNomenType_name, AnnotNomenType_value)
	proto.RegisterEnum("protob.Approach", Approach_name, Approach_value)
	proto.RegisterType((*Void)(nil), "protob.Void")
	proto.RegisterType((*Pong)(nil), "protob.Pong")
	proto.RegisterType((*Version)(nil), "protob.Version")
	proto.RegisterType((*Params)(nil), "protob.Params")
	proto.RegisterType((*Output)(nil), "protob.Output")
	proto.RegisterType((*NameString)(nil), "protob.NameString")
	proto.RegisterType((*Verification)(nil), "protob.Verification")
	proto.RegisterType((*ResultData)(nil), "protob.ResultData")
}

func init() { proto.RegisterFile("protob.proto", fileDescriptor_e471450a6e94b5eb) }

var fileDescriptor_e471450a6e94b5eb = []byte{
	// 1214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x56, 0x51, 0x73, 0xda, 0x46,
	0x10, 0x36, 0x16, 0x60, 0xb4, 0x60, 0x2c, 0x2e, 0x99, 0x8c, 0x9a, 0x69, 0xa7, 0x44, 0x49, 0x5b,
	0xea, 0x26, 0x76, 0xc7, 0xe9, 0x43, 0xfa, 0xd4, 0x62, 0x87, 0xa4, 0xcc, 0x24, 0x40, 0x04, 0xf1,
	0x34, 0x79, 0xb9, 0x39, 0xd0, 0x81, 0x35, 0x16, 0x77, 0xf4, 0x74, 0x72, 0xc3, 0x2f, 0xe8, 0x5b,
	0xdf, 0xfa, 0x03, 0xfa, 0x13, 0xfa, 0x8b, 0xfa, 0x57, 0x3a, 0x77, 0x27, 0x09, 0x81, 0xdd, 0x27,
	0x6e, 0xbf, 0xfd, 0x56, 0xdc, 0x7e, 0xb7, 0xbb, 0x77, 0xd0, 0x58, 0x09, 0x2e, 0xf9, 0xf4, 0x44,
	0xff, 0xa0, 0xaa, 0xb1, 0xbc, 0x2a, 0x94, 0x2f, 0x79, 0x18, 0x78, 0x9f, 0x43, 0x79, 0xc4, 0xd9,
	0x02, 0xdd, 0x87, 0xca, 0x0d, 0x89, 0x12, 0xea, 0x96, 0xda, 0xa5, 0x8e, 0xed, 0x1b, 0xc3, 0xfb,
	0x11, 0x0e, 0x2e, 0xa9, 0x88, 0x43, 0xce, 0x90, 0x0b, 0x07, 0x37, 0x66, 0x99, 0x52, 0x32, 0x53,
	0x85, 0x4e, 0x93, 0x30, 0x0a, 0xdc, 0x7d, 0x13, 0xaa, 0x0d, 0xef, 0xdf, 0x12, 0x54, 0x47, 0x44,
	0x90, 0x65, 0x8c, 0x10, 0x94, 0x25, 0xfd, 0x24, 0xd3, 0x38, 0xbd, 0x46, 0x9f, 0x41, 0x8d, 0x71,
	0x3c, 0x25, 0x6b, 0x1a, 0xeb, 0xb8, 0x9a, 0x7f, 0xc0, 0xf8, 0xb9, 0x32, 0xd1, 0x43, 0xa8, 0x45,
	0x84, 0x2d, 0x12, 0xb2, 0xa0, 0xae, 0xa5, 0x43, 0x72, 0x1b, 0x7d, 0x03, 0x47, 0x01, 0x95, 0x74,
	0x26, 0x71, 0x4e, 0x29, 0xeb, 0xe8, 0xa6, 0x81, 0xdf, 0x64, 0x44, 0x0f, 0x1a, 0x37, 0x54, 0x84,
	0xf3, 0x70, 0x46, 0xa4, 0xda, 0x73, 0x45, 0xb3, 0xb6, 0x30, 0xf4, 0x18, 0x0e, 0x25, 0xbf, 0xa6,
	0x2c, 0xc6, 0x44, 0xf0, 0x84, 0x05, 0x6e, 0xb5, 0x5d, 0xea, 0x54, 0xfc, 0x86, 0x01, 0xbb, 0x1a,
	0x53, 0x79, 0xc7, 0x3c, 0x11, 0x33, 0x1a, 0xbb, 0x07, 0x6d, 0xab, 0x53, 0xf1, 0x33, 0xd3, 0xfb,
	0xdb, 0x82, 0xea, 0x30, 0x91, 0xab, 0x44, 0xaa, 0x0c, 0x03, 0x22, 0x33, 0xf1, 0xf4, 0x1a, 0x7d,
	0x05, 0xcd, 0x79, 0xc8, 0x02, 0x2a, 0x70, 0xa6, 0x9b, 0xd1, 0xe7, 0xd0, 0xa0, 0x99, 0xae, 0x4f,
	0xa1, 0x46, 0x56, 0x2b, 0xc1, 0xc9, 0xec, 0xca, 0xb5, 0xda, 0x56, 0xa7, 0x79, 0xe6, 0x9c, 0xa4,
	0x27, 0xd6, 0x4d, 0x71, 0x3f, 0x67, 0xdc, 0xde, 0x72, 0xf9, 0x8e, 0x2d, 0x17, 0x05, 0xac, 0xec,
	0x08, 0xf8, 0x1d, 0xb4, 0xb2, 0x35, 0x36, 0x92, 0x51, 0x93, 0xb7, 0xed, 0x3b, 0x99, 0xe3, 0x65,
	0x8a, 0xdf, 0xa5, 0xf6, 0xc1, 0x9d, 0x6a, 0x3f, 0x82, 0x86, 0xe4, 0x92, 0x44, 0xd8, 0xec, 0xc3,
	0xad, 0xe9, 0x5d, 0xd5, 0x35, 0x36, 0xd1, 0x10, 0xfa, 0x16, 0x1c, 0x43, 0x99, 0x11, 0x16, 0x84,
	0x4a, 0xa1, 0xd8, 0xb5, 0x35, 0xed, 0x48, 0xe3, 0x17, 0x39, 0x8c, 0xbe, 0x04, 0x13, 0x89, 0x19,
	0x59, 0xd2, 0xd8, 0x05, 0xcd, 0x02, 0x0d, 0x0d, 0x14, 0x82, 0x3a, 0x50, 0x31, 0xae, 0x7a, 0xdb,
	0xea, 0xd4, 0xcf, 0x50, 0x26, 0x98, 0xf2, 0x8e, 0xa5, 0x08, 0xd9, 0xc2, 0x37, 0x04, 0xef, 0x2f,
	0x0b, 0x60, 0x83, 0xa2, 0x36, 0xd4, 0x67, 0x44, 0x04, 0x21, 0x23, 0x51, 0x28, 0xd7, 0xfa, 0xb8,
	0x2a, 0x7e, 0x11, 0x52, 0xda, 0xdd, 0x50, 0x31, 0x25, 0x32, 0x5c, 0x66, 0xc5, 0x97, 0xd9, 0xea,
	0x94, 0xd5, 0x57, 0xb5, 0xe6, 0xb6, 0xaf, 0xd7, 0x0a, 0xe3, 0x41, 0x10, 0x6b, 0x9d, 0xf7, 0x7d,
	0xbd, 0x56, 0xfb, 0x27, 0x8c, 0x71, 0x89, 0x19, 0x5f, 0x52, 0x96, 0xaa, 0x0b, 0x1a, 0x1a, 0x28,
	0x04, 0xfd, 0x0c, 0x4e, 0x81, 0x80, 0xe5, 0x7a, 0x65, 0x84, 0x6d, 0x9e, 0x3d, 0xc8, 0xcf, 0x3e,
	0x67, 0x4f, 0xd6, 0x2b, 0xea, 0x37, 0xc9, 0x96, 0xad, 0x04, 0xe7, 0xf3, 0x79, 0x4c, 0x25, 0x8e,
	0x25, 0x11, 0x32, 0x13, 0xdc, 0x60, 0x63, 0x05, 0xa1, 0x2f, 0x00, 0x52, 0x0a, 0x65, 0x41, 0x2a,
	0xb5, 0x6d, 0x90, 0x1e, 0x0b, 0xd4, 0x17, 0x7e, 0xe7, 0x22, 0x88, 0xf1, 0x94, 0xce, 0xb9, 0xa0,
	0x2e, 0xb4, 0xad, 0x8e, 0xed, 0xd7, 0x35, 0x76, 0xae, 0x21, 0x95, 0x87, 0xa1, 0x90, 0xb9, 0xa4,
	0x42, 0x8b, 0x6d, 0xfb, 0xa0, 0xa1, 0xae, 0x42, 0xd0, 0x8b, 0x9d, 0x26, 0x6b, 0xb4, 0x4b, 0x9d,
	0xfa, 0xd9, 0xfd, 0x2c, 0x87, 0xcb, 0x82, 0x6f, 0xbb, 0xf5, 0xbc, 0x3f, 0xf7, 0xa1, 0x51, 0x74,
	0xa3, 0xe7, 0x50, 0x9f, 0xd2, 0x58, 0x62, 0x41, 0xe3, 0x24, 0x32, 0xa3, 0xa2, 0x70, 0xb0, 0xbe,
	0x46, 0x5f, 0x12, 0x49, 0x7c, 0x50, 0x34, 0x63, 0xa3, 0x9f, 0xa0, 0xb5, 0x12, 0x74, 0x4e, 0x85,
	0xa0, 0x41, 0x1a, 0xa9, 0xa6, 0x89, 0xf5, 0x3f, 0xa1, 0x4e, 0x4e, 0x36, 0xa0, 0x2a, 0x24, 0x27,
	0x20, 0x92, 0xe0, 0xb4, 0xa5, 0x31, 0x4b, 0xcc, 0xa9, 0x57, 0xfc, 0xa6, 0xc2, 0xc7, 0x06, 0x1e,
	0x24, 0x4b, 0x74, 0x02, 0xf7, 0x0a, 0x4c, 0xfc, 0x5b, 0x62, 0x2a, 0xc8, 0x94, 0x42, 0x6b, 0x43,
	0x7e, 0x67, 0x1c, 0x6a, 0x6c, 0x08, 0x2a, 0x45, 0x48, 0x4d, 0x69, 0x54, 0xfc, 0xcc, 0x54, 0xe3,
	0x92, 0x0a, 0xc1, 0x45, 0x5a, 0x17, 0xc6, 0xf0, 0xfe, 0xa9, 0x02, 0x6c, 0xb6, 0x8a, 0x9e, 0x40,
	0xb3, 0xf8, 0x77, 0x61, 0x90, 0xd6, 0x6a, 0x63, 0xf3, 0x4f, 0xfd, 0x00, 0x1d, 0x43, 0xab, 0xc8,
	0x92, 0xa1, 0x8c, 0x68, 0x3a, 0x65, 0x8e, 0x36, 0xc4, 0x89, 0x82, 0xd5, 0xc0, 0x95, 0xe4, 0x13,
	0x67, 0xea, 0x5b, 0xa6, 0xb0, 0x0f, 0xb4, 0xdd, 0xd7, 0xa5, 0xb0, 0x24, 0x72, 0x76, 0x45, 0x03,
	0x5c, 0xa8, 0xef, 0x7a, 0x8a, 0xa9, 0xf6, 0x41, 0xa7, 0x70, 0x2f, 0xa3, 0x14, 0x1b, 0xc8, 0xa4,
	0x86, 0x52, 0xd7, 0x45, 0xa1, 0x8f, 0x5e, 0x80, 0xbb, 0x09, 0x60, 0x9c, 0x85, 0x33, 0x12, 0xe1,
	0x38, 0x5c, 0xae, 0x22, 0x9a, 0x26, 0xfe, 0x20, 0x8f, 0x4a, 0xdd, 0x63, 0xed, 0x45, 0x3f, 0xc0,
	0x83, 0xdb, 0x91, 0xf3, 0x24, 0x8a, 0x74, 0x8b, 0xd8, 0xfe, 0xfd, 0xdd, 0xb8, 0x57, 0x49, 0x14,
	0xa9, 0x1c, 0x66, 0x89, 0x10, 0x94, 0x49, 0x93, 0x43, 0xcd, 0xe4, 0x90, 0x62, 0x59, 0x0e, 0x19,
	0xa5, 0x98, 0x83, 0xe9, 0x0c, 0x94, 0xba, 0x76, 0x72, 0xd8, 0x04, 0xec, 0xe4, 0x00, 0x26, 0x87,
	0x3c, 0xea, 0x56, 0x0e, 0xb7, 0x23, 0x75, 0x0e, 0x75, 0x93, 0xc3, 0x6e, 0x9c, 0xce, 0x41, 0x5d,
	0x35, 0x6b, 0xc6, 0xd9, 0x7a, 0xa9, 0x3b, 0xa9, 0xe6, 0x67, 0xa6, 0xde, 0x7a, 0x44, 0xe2, 0x38,
	0xef, 0x17, 0xbc, 0x22, 0xf2, 0xca, 0x3d, 0xd4, 0x1f, 0x43, 0xdb, 0xae, 0x11, 0x91, 0x57, 0x77,
	0x04, 0x08, 0xc2, 0xae, 0xdd, 0xe6, 0x5d, 0x01, 0x3e, 0x61, 0xd7, 0xe8, 0x19, 0xec, 0xa0, 0x38,
	0x0c, 0x62, 0xf7, 0xc8, 0x94, 0xf7, 0xb6, 0xa7, 0x1f, 0xc4, 0xea, 0x1e, 0xa2, 0x41, 0x28, 0x71,
	0x10, 0xc6, 0x92, 0xb0, 0x19, 0x75, 0x1d, 0x53, 0x9e, 0x0a, 0x7c, 0x99, 0x62, 0xe8, 0x29, 0xa0,
	0x58, 0xd2, 0x25, 0xde, 0x66, 0xb6, 0x34, 0xd3, 0x51, 0x9e, 0x5e, 0x91, 0xfd, 0x3d, 0x80, 0x3e,
	0x59, 0x33, 0x0e, 0x91, 0x1e, 0x87, 0xad, 0xac, 0x8b, 0xdf, 0x2a, 0x8f, 0x9e, 0x84, 0xf6, 0x32,
	0x5b, 0x1e, 0xbf, 0x03, 0x3b, 0xc7, 0x51, 0x0d, 0xca, 0x83, 0xe1, 0xa0, 0xe7, 0xec, 0x21, 0x1b,
	0x2a, 0xbd, 0x5f, 0xbb, 0x17, 0x13, 0xa7, 0xa4, 0x96, 0xaf, 0xde, 0x7f, 0xfc, 0xf8, 0xc1, 0xd9,
	0x47, 0x2d, 0x38, 0x1c, 0x75, 0xfd, 0x49, 0xbf, 0xfb, 0x06, 0x1b, 0xaf, 0x55, 0x84, 0x0c, 0xab,
	0x7c, 0xfc, 0x1a, 0x9a, 0xdb, 0x93, 0x17, 0x35, 0xa0, 0x36, 0x18, 0xe2, 0xee, 0x60, 0x30, 0x9c,
	0x38, 0x7b, 0x08, 0xa0, 0x3a, 0x1e, 0xe1, 0xc1, 0xf0, 0xd2, 0x29, 0x29, 0xcf, 0xc5, 0xf0, 0xed,
	0xb9, 0xb6, 0xf6, 0xd1, 0x21, 0xd8, 0xe3, 0xf7, 0xe7, 0xa9, 0xd3, 0x3a, 0x7e, 0x02, 0xb5, 0xec,
	0xfa, 0x56, 0xae, 0x5f, 0x7a, 0xef, 0xfd, 0xfe, 0x78, 0xd2, 0xbf, 0x30, 0xfb, 0x3b, 0xef, 0x7e,
	0xe8, 0x8d, 0x9d, 0xd2, 0xd9, 0x1f, 0x25, 0xa8, 0xbd, 0x1e, 0xbc, 0xd2, 0x0f, 0x02, 0xf4, 0x04,
	0xca, 0x23, 0x75, 0x49, 0x35, 0xf2, 0xf9, 0xc9, 0xc3, 0xe0, 0x61, 0x6e, 0xa9, 0x67, 0x9a, 0xb7,
	0x87, 0xbe, 0x06, 0xeb, 0x92, 0x8a, 0x1d, 0xd2, 0x51, 0x61, 0xe4, 0xaa, 0x57, 0x85, 0xb7, 0x87,
	0x9e, 0x81, 0xad, 0xbe, 0x6b, 0x2e, 0xcc, 0x66, 0xfe, 0x11, 0xfd, 0x22, 0x7b, 0x98, 0xdb, 0xe6,
	0xfd, 0xe2, 0xed, 0x9d, 0x3f, 0xfe, 0xf8, 0x68, 0x11, 0xca, 0xab, 0x64, 0x7a, 0x32, 0xe3, 0xcb,
	0xd3, 0x85, 0xbe, 0x3d, 0x4f, 0x17, 0xcc, 0xbc, 0x55, 0x4e, 0x0d, 0x7b, 0x6a, 0x1e, 0x8f, 0xcf,
	0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x93, 0x63, 0x60, 0x53, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GNFinderClient is the client API for GNFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GNFinderClient interface {
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error)
	Ver(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Version, error)
	FindNames(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Output, error)
}

type gNFinderClient struct {
	cc *grpc.ClientConn
}

func NewGNFinderClient(cc *grpc.ClientConn) GNFinderClient {
	return &gNFinderClient{cc}
}

func (c *gNFinderClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/protob.GNFinder/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNFinderClient) Ver(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/protob.GNFinder/Ver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNFinderClient) FindNames(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/protob.GNFinder/FindNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GNFinderServer is the server API for GNFinder service.
type GNFinderServer interface {
	Ping(context.Context, *Void) (*Pong, error)
	Ver(context.Context, *Void) (*Version, error)
	FindNames(context.Context, *Params) (*Output, error)
}

func RegisterGNFinderServer(s *grpc.Server, srv GNFinderServer) {
	s.RegisterService(&_GNFinder_serviceDesc, srv)
}

func _GNFinder_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNFinderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNFinder/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNFinderServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNFinder_Ver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNFinderServer).Ver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNFinder/Ver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNFinderServer).Ver(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNFinder_FindNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNFinderServer).FindNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.GNFinder/FindNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNFinderServer).FindNames(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

var _GNFinder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protob.GNFinder",
	HandlerType: (*GNFinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GNFinder_Ping_Handler,
		},
		{
			MethodName: "Ver",
			Handler:    _GNFinder_Ver_Handler,
		},
		{
			MethodName: "FindNames",
			Handler:    _GNFinder_FindNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protob.proto",
}
