name: Lint

on: 
  push:
    branches: [ master ]

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
