name: Test

on: 
  push:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Vet
      run: go vet ./...

    # - name: Upload coverage reports to Codecov
    #     uses: codecov/codecov-action@v4.0.1
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #
    # - name: CodeCovif
    #   if: matrix.platform != 'windows-latest'
    #   run: bash <(curl -s https://codecov.io/bash)
