name: Test

on: 
  push:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Vet
      run: go vet ./...

    - name: CodeCovif
      if: matrix.platform != 'windows-latest'
      run: bash <(curl -s https://codecov.io/bash)
